<?php


add_action('init', function () {
    register_post_type('notification', array(
        'labels' => array(
            'name' => 'Notifications',
            'singular_name' => 'Notification',
            'menu_name' => 'Notification',
            'all_items' => 'All Notification',
            'edit_item' => 'Edit Notification',
            'view_item' => 'View Notification',
            'view_items' => 'View Notification',
            'add_new_item' => 'Add New Notification',
            'add_new' => 'Add New Notification',
            'new_item' => 'New Notification',
            'parent_item_colon' => 'Parent Notification:',
            'search_items' => 'Search Notification',
            'not_found' => 'No notification found',
            'not_found_in_trash' => 'No notification found in Trash',
            'archives' => 'Notification Archives',
            'attributes' => 'Notification Attributes',
            'insert_into_item' => 'Insert into notification',
            'uploaded_to_this_item' => 'Uploaded to this notification',
            'filter_items_list' => 'Filter notification list',
            'filter_by_date' => 'Filter notification by date',
            'items_list_navigation' => 'Notification list navigation',
            'items_list' => 'Notification list',
            'item_published' => 'Notification published.',
            'item_published_privately' => 'Notification published privately.',
            'item_reverted_to_draft' => 'Notification reverted to draft.',
            'item_scheduled' => 'Notification scheduled.',
            'item_updated' => 'Notification updated.',
            'item_link' => 'Notification Link',
            'item_link_description' => 'A link to a notification.',
        ),
        'public' => true,
        'show_in_rest' => true,
        'menu_position' => 2,
        'menu_icon' => 'dashicons-welcome-comments',
        'supports' => array(
            0 => 'title',
            1 => 'editor',
        ),
        'taxonomies' => array(
            0 => 'category',
        ),
        'delete_with_user' => false,
    ));

    register_post_type('tiktok_order', array(
        'labels' => array(
            'name' => 'Orders',
            'singular_name' => 'Order',
            'menu_name' => 'Orders',
            'all_items' => 'All Orders',
            'edit_item' => 'Edit Order',
            'view_item' => 'View Order',
            'view_items' => 'View Orders',
            'add_new_item' => 'Add New Order',
            'add_new' => 'Add New Order',
            'new_item' => 'New Order',
            'parent_item_colon' => 'Parent Order:',
            'search_items' => 'Search Orders',
            'not_found' => 'No orders found',
            'not_found_in_trash' => 'No orders found in Trash',
            'archives' => 'Order Archives',
            'attributes' => 'Order Attributes',
            'insert_into_item' => 'Insert into order',
            'uploaded_to_this_item' => 'Uploaded to this order',
            'filter_items_list' => 'Filter orders list',
            'filter_by_date' => 'Filter orders by date',
            'items_list_navigation' => 'Orders list navigation',
            'items_list' => 'Orders list',
            'item_published' => 'Order published.',
            'item_published_privately' => 'Order published privately.',
            'item_reverted_to_draft' => 'Order reverted to draft.',
            'item_scheduled' => 'Order scheduled.',
            'item_updated' => 'Order updated.',
            'item_link' => 'Order Link',
            'item_link_description' => 'A link to a order.',
        ),
        'public' => true,
        'hierarchical' => true,
        'show_in_rest' => true,
        'menu_position' => 1,
        'menu_icon' => 'dashicons-cart',
        'supports' => array(
            0 => 'title',
            1 => 'comments',
            2 => 'custom-fields',
        ),
        'taxonomies' => array(
            0 => 'category',
        ),
        'delete_with_user' => true,
    ));
});

add_action('acf/include_fields', function () {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
        'key' => 'group_6812675b8db81',
        'title' => 'Design Infomation',
        'fields' => array(
            array(
                'key' => 'field_6812677e8a305',
                'label' => 'Designer',
                'name' => 'designer',
                'aria-label' => '',
                'type' => 'user',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'role' => array(
                    0 => 'designer',
                ),
                'return_format' => 'id',
                'multiple' => 0,
                'allow_null' => 1,
                'allow_in_bindings' => 0,
                'bidirectional' => 0,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key' => 'field_681273554b8ba',
                'label' => 'Design Link',
                'name' => 'design_link',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_681273d8c277d',
                'label' => 'Deadline',
                'name' => 'deadline',
                'aria-label' => '',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'd/m/Y',
                'return_format' => 'd/m/Y',
                'first_day' => 1,
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_681274f6c28d5',
                'label' => 'Status',
                'name' => 'status',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    1 => 'Waiting for Design',
                    2 => 'Revising Design',
                    3 => 'Completed',
                ),
                'default_value' => 1,
                'return_format' => 'array',
                'multiple' => 0,
                'allow_null' => 0,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'tiktok_order',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_68150abe88c8b',
        'title' => 'Notification',
        'fields' => array(
            array(
                'key' => 'field_68150abec7b4c',
                'label' => 'User',
                'name' => 'user_id',
                'aria-label' => '',
                'type' => 'user',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'role' => '',
                'return_format' => 'id',
                'multiple' => 0,
                'allow_null' => 0,
                'allow_in_bindings' => 0,
                'bidirectional' => 0,
                'bidirectional_target' => array(
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'notification',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_6813962e0744a',
        'title' => 'Setting',
        'fields' => array(
            array(
                'key' => 'field_6813962ee7cf6',
                'label' => 'Access Token',
                'name' => 'access_token',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_681397dc0df75',
                'label' => 'App Secret',
                'name' => 'app_secret',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_681397e70df76',
                'label' => 'App Key',
                'name' => 'app_key',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_681397f10df77',
                'label' => 'Shop Cipher',
                'name' => 'shop_cipher',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_681397fa0df78',
                'label' => 'Shop Id',
                'name' => 'shop_id',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_681398030df79',
                'label' => 'Version',
                'name' => 'version',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 202309,
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '101',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_6812709e69688',
        'title' => 'User',
        'fields' => array(
            array(
                'key' => 'field_6812709e804dd',
                'label' => 'Phone',
                'name' => 'phone',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 1,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'user_form',
                    'operator' => '==',
                    'value' => 'all',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
});
